config/routes.rb
Rails.application.routes.draw do
  root 'people#index'

  resources :people
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord

  def self.genders
    ['Male', 'Female', 'Other']
  end

  validates_presence_of :name, :age, :eye_color, :hair_color, :gender, :alive
  validates_inclusion_of :gender, in: genders
  validates_inclusion_of :age, in: (18..100).to_a, message: 'Needs to be Between 18 and 100.'

  def info
    "#{name} is #{age} year old #{gender} with #{eye_color} eyes and #{hair_color} hair who is alive: #{alive_display}."
  end
  
  def alive_display
    alive ? 'yes' : 'no'
  end

  def names
    "#{name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  
  def index
    @persons = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new 
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private
    def person_params
      params.require(:person).permit(:name, :age, :eye_color, :hair_color, :gender, :alive)
    end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  
  def index
    @persons = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new 
  end

  def create
    @person = Person.new(person_params)
    if @person.save
      redirect_to person_path(@person)
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      redirect_to person_path(@person)
    else
      render :edit
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to persons_path
  end

  private
    def person_params
      params.require(:person).permit(:name, :age, :eye_color, :hair_color, :gender, :alive)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Persons</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<% if @person.errors.any? %>
  <h3> <%= @person.errors.count %> Errors </h3>
  <ul>
    <% @person.errors.full_messages.each do |message| %>
      <li> <%= message %> </li>
    <% end %>
  </ul>
<% end %>

<%= form_for @person do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div>
    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>
  </div>

  <div>
    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>
  </div>

  <div>
    <%= f.label :gender %>
    <%= f.select :gender, Person.genders %>
  </div>

  <div>
    <%= f.label :alive %>
    <%= f.select :alive, [['Yes', true,], ['No', false]] %>
  </div>

  <%= f.submit %>

<% end %>

app/views/people/edit.html.erb
<h1>Edit This Person</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', person_path %>

app/views/people/index.html.erb
<h1>People</h1>

<% if @persons.any? %>
  
  <% @persons.each do |person| %>
    <div>
      <%= link_to person.info, person_path(person) %>
    </div>
  <% end %>

<% else %>
  <h3>No People Found, Please Enter One!</h3>
<% end %>

<hr />
<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>Enter a New Person</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<h1> <%= @person.names %> </h1>

<ul>
  <li>Age: <%= @person.age %> </li>
  <li>Gender: <%= @person.gender %></li>
  <li>Eye Color: <%= @person.eye_color %></li>
  <li>Hair Color: <%= @person.hair_color %></li>
  <li>Alive: <%= @person.alive_display %></li>
  <li>
    <%= link_to 'Edit', edit_person_path(@person) %>
    <%= link_to 'Delete', person_path(@person), method: :delete,method: :delete, data: {confirm: 'Really Delete?'} %>
  </li>
</ul>

<%= link_to 'Home', people_path %>

app/views/persons/_form.html.erb
<%= form_for @person do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div>
    <%= f.label :eye_color %>
    <%= f.text_field :eye_color %>
  </div>

  <div>
    <%= f.label :hair_color %>
    <%= f.text_field :hair_color %>
  </div>

  <div>
    <%= f.label :gender %>
    <%= f.select :gender, Person.genders %>
  </div>

  <div>
    <%= f.label :alive %>
    <%= f.select :alive, [['Yes', true,], ['No', false]] %>
  </div>

  <%= f.submit %>

<% end %>

app/views/persons/new.html.erb
<h1>Enter a New Person</h1>

<%= render(partial: 'form') %>

<%= link_to 'Back', persons_path %>